name: CI with React App

on:
  push:
    branches: [main]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Echo
        run: echo "Hello World!"
